var CatFacts = function() {};
(function(){

var lastCatFact
var interestingFacts = [
'Cats and humans have identical regions in the brain responsible for emotion.',
'A cat\'s brain is more similar to a human brain than that of a dog.',
'Cats can rotate each ear independently from the other in 180 degrees.',
'Cat hearing stops at 65kHz; human hearing stops at 20kHz.',
'Cats see about 6 times better than humans at night.',
'Cats can judge within 3 inches the precise location of a sound being made 1 yard away.',
'Cats can be right-pawed or left-pawed.',
'Cats cannot see directly under their nose.',
'Cats express their present state of mind through their tail.',
'Cats are the only animals that walk on their toes.',
'Cats were worshipped as holy in Ancient Egypt and granted great respect in every household.',
'Phoenician ships likely brought the first domesticated cats to Europe in about 900 BC.',
'Ancient Egyptians shaved their eyebrows in mourning when the family cat died.',
'In Siam, a cat rode in a chariot at the head of a parade celebrating the new king.',
'Most cats adore sardines.',
'Cats use their whiskers to measure distances and changes in air pressure.',
'Cat whiskers are very sensitive to touch.',
'Abraham Lincoln kept four cats at the White House during his presidency.',
'Cats purr at the same frequency as an idling diesel engine.',
'Nikola Tesla was inspired to study electricity after his cat static-shocked him in his youth.',
'Isaac Newton invented the cat-flap.',
'Cats use their tails for balance and have nearly 30 individual bones in them.',
'Even though Napoleon was known as a ruthless conqueror, he was always very afraid of cats.',
'A kitten\'s eyes are always blue at first.',
'A cat can jump as high as seven times as it is tall.',
'Kittens begin dreaming at just over one week old.',
'Every cat\'s nose is unique, and no two nose-prints are the same.',
'The Pilgrims were the first to introduce cats to North America.',
'Cats purr to communicate.',
'A group of kittens is called a kindle.',
'The British Government owns thousands of cats, deployed in government buildings to get rid of mice.',
'Cats are more active during the evening hours.',
'Cats have a field of vision of about 185 degrees.',
'Cats have the AB blood type, which is also found in humans.',
'Cats have a homing ability that uses their biological clock, the sun\'s angle and the Earth\'s magnetic field.',
'A cat taken far from its home can return to it thanks to remarkable homing instincts.',
'Cats successfully catch mice in about one out of three attempts.',
'Female cats tend to be right pawed, while male cats are more often left pawed.',
'The first cat in space was a French cat named Felicette, sent in 1963. She survived the trip.',
'A cat can travel at a top speed of approximately 31 mph (49 km/h) over a short distance.',
'Ancient Egyptians worshipped the goddess Bast, who had a woman\'s body and a cat\'s head.',
'Cats almost never meow at each other, and mostly do so only to communicate with humans.',
'Approximately one third of cat owners think their pets are able to read their minds.',
'In Japan, cats are thought to have the power to turn into powerful spirits when they die.',
'According to Buddhist legend, the body of the cat is the temporary resting place of spiritual people.',
'A cat\'s heart beats nearly twice as fast as a human heart.',
'Cats sweat only through their paws.',
'When cats are happy or pleased, they momentarily squeeze their eyes shut.',
'Cryptocat\'s lead developer lives with a cat named Sprite. She is super cute and awesome!',
'Cats can make over one hundred different vocalizations.',
'Cats purr at a frequency that promotes bone density and helps with bone healing.',
'Every year nearly four million cats are eaten in Asia.',
'On average, cats spend two-thirds of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life.',
'Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.',
'When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.',
'The technical term for a cat\'s hairball is a bezoar.',
'A group of cats is called a clowder.',
'Female cats tend to be right pawed, while male cats are more often left pawed. Interestingly, while 90% of humans are right handed, the remaining 10% of lefties also tend to be male.',
'A cat cannot climb head first down a tree because its claws are curved the wrong way.',
'A cat can\'t climb head first down a tree because every claw on a cat\'s paw points the same way. To get down from a tree, a cat must back down.',
'Cats make about 100 different sounds. Dogs make only about 10.',
'A cat\'s brain is biologically more similar to a human brain than it is to a dog\'s. Both humans and cats have identical regions in their brains that are responsible for emotions.',
'There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.',
'Approximately 24 cat skins can make a coat.',
'The oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.',
'Cats are the most popular pet in North America.',
'Cats are North America\'s most popular pets: there are 73 million cats compared to 63 million dogs.',
'Over 30% of households in North America own a cat.',
'The group of words associated with cat (catt, cath, chat, katze) stem from the Latin catus, meaning domestic cat, as opposed to feles, or wild cat.',
'Approximately 40,000 people are bitten by cats in the U.S. annually.',
'According to Hebrew legend, Noah prayed to God for help protecting all the food he stored on the ark from being eaten by rats. In reply, God made the lion sneeze, and out popped a cat.',
'A cat\'s hearing is better than a dog\'s. And a cat can hear high-frequency sounds up to two octaves higher than a human.',
'A cat can travel at a top speed of approximately 31 mph (49 km) over a short distance.',
'A cat can jump up to five times its own height in a single bound.',
'Some cats have survived falls of over 65 feet (20 meters), due largely to their righting reflex. The eyes and balance organs in the inner ear tell it where it is in space so the cat can land on its feet. Even cats without a tail have this ability.',
'A cat rubs against people to mark them as their territory.',
'A cat rubs against people not only to be affectionate but also to mark out its territory with scent glands around its face. The tail area and paws also carry the cat\'s scent.',
'Researchers are unsure exactly how a cat purrs. Most veterinarians believe that a cat purrs by vibrating vocal folds deep in the throat. To do this, a muscle in the larynx opens and closes the air passage about 25 times per  second.',
'When a family cat died in ancient Egypt, family members would mourn by shaving off their eyebrows. The cat was embalmed with a sculpted wooden mask and the tiny mummy was placed in the family tomb or in a pet cemetery with tiny mummies of mice.',
'In 1888, more than 300,000 mummified cats were found an Egyptian cemetery. They were stripped of their wrappings and carted off to be used by farmers in England and the U.S. for fertilizer.',
'Most cats give birth to a litter of between one and nine kittens. The largest known litter ever produced was 19 kittens, of which 15 survived.',
'Smuggling a cat out of ancient Egypt was punishable by death. Phoenician traders eventually succeeded in smuggling felines, which they sold to rich people in Athens and other important cities.',
'The earliest ancestor of the modern cat lived about 30 million years ago. Scientists called it the Proailurus, which means first cat in Greek. The group of animals that pet cats belong to emerged around 12 million years ago.',
'The biggest wildcat today is the Siberian Tiger. It can be more than 12 feet (3.6 m) long (about the size of a small car) and weigh up to 700 pounds (317 kg).',
'The smallest wildcat today is the Black-footed cat. The females are less than 20 inches (50 cm) long and can weigh as little as 2.5 lbs (1.2 kg).',
'Many Egyptians worshipped the goddess Bast, who had a woman\'s body and a cat\'s head.',
'While many parts of Europe and North America consider the black cat a sign of bad luck, in Britain and Australia, black cats are considered lucky.',
'The most popular pedigreed cat is the Persian cat, followed by the Maine Coon cat and the Siamese cat.',
'The smallest pedigreed cat is a Singapura, which can weigh just 4 lbs (1.8 kg), or about five large cans of cat food.',
'The largest pedigreed cats are Maine Coon cats, which can weigh 25 lbs (11.3 kg), or nearly twice as much as an average cat weighs.',
'Some Siamese cats are cross-eyed to compensate for abnormal optic wiring.',
'Researchers believe the word tabby comes from Attabiyah, a neighborhood in Baghdad, Iraq. Tabbies got their name because their striped coats resembled the famous wavy patterns in the silk produced in this city.',
'Cats hate the water because their fur does not insulate well when it\'s wet.',
'The Turkish Van, however, is one cat that likes swimming. Bred in central Asia, its coat has a unique texture that makes it water resistant.',
'The Egyptian Mau is probably the oldest breed of cat. In fact, the breed is so ancient that its name is the Egyptian word for cat.',
'A cat usually has about 12 whiskers on each side of its face.',
'Scientists believe grass appears red to cats.',
'In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat.',
'The little tufts of hair in a cat\'s ear that help keep out dirt direct sounds into the ear, and insulate the ears are called ear furnishings.',
'The ability of a cat to find its way home is called psi-traveling. Experts think cats either use the angle of the sunlight to find their way or that cats have magnetized cells in their brains that act as compasses.',
'Isaac Newton invented the cat flap. Newton was experimenting in a pitch-black room. Spithead, one of his cats, kept opening the door and wrecking his experiment. The cat flap kept both Newton and Spithead happy.',
'The world\'s rarest coffee, Kopi Luwak, comes from Indonesia where a wildcat known as the luwak lives. The cat eats coffee berries and the coffee beans inside pass through the stomach. The beans are harvested from the cat\'s dung heaps and then cleaned and roasted. Kopi Luwak sells for about $500 for a 450 g (1 lb) bag.',
'A cat\'s jaw can\'t move sideways, so a cat can\'t chew large  chunks of food.',
'A cat almost never meows at another cat, mostly just humans. Cats typically will spit, purr, and hiss at other cats.',
'A cat\'s back is extremely flexible because it has up to 53 loosely fitting vertebrae. Humans only have 34.',
'Approximately 1/3 of cat owners think their pets are able to read their minds.',
'All cats have claws, and all except the cheetah sheath them when at rest.',
'Two members of the cat family are distinct from all others: the clouded leopard and the cheetah. The clouded leopard does not roar like other big cats, nor does it groom or rest like small cats. The cheetah is unique because it is a running cat; all others are leaping cats. They are leaping cats because they slowly stalk their prey and then leap on it.',
'A cat lover is called an Ailurophilia (Greek: cat+lover).',
'In Japan, cats are thought to have the power to turn into super spirits when they die. This may be because according to the Buddhist religion, the body of the cat is the temporary resting place of very spiritual people.',
'Most cats had short hair until about 100 years ago, when it became fashionable to own cats and experiment with breeding.',
'Cats have 32 muscles that control the outer ear (humans have only 6). A cat can independently rotate its ears 180 degrees.',
'During the nearly 18 hours a day that kittens sleep, an important growth hormone is released. ',
'One reason that kittens sleep so much is because a growth hormone is released only during sleep.',
'Cats have about 130,000 hairs per square inch (20,155 hairs per square centimeter).',
'The heaviest cat on record is Himmy, a Tabby from Queensland, Australia. He weighed nearly 47 pounds (21 kg).',
'The oldest cat on record was Creme Puff from Austin, Texas, who lived for 38 years. ',
'A cat typically can live up to 20 years, which is equivalent to about 96 human years.',
'The lightest cat on record is a blue point Himalayan called Tinker Toy, who weighed 1 pound, 6 ounces (616 g). Tinker Toy was 2.75 inches (7 cm) tall and 7.5 inches (19 cm) long.',
'The tiniest cat on record is Mr. Pebbles, a 2-year-old cat that weighed 3 lbs (1.3 k) and was 6.1 inches (15.5 cm) high.',
'A commemorative tower was built in Scotland for a cat named Towser, who caught nearly 30,000 mice in her lifetime.',
'In the 1750s, Europeans introduced cats into the Americas to control pests.',
'The first cat show was organized in 1871 in London. Cat shows later became a worldwide craze.',
'The first cartoon cat was Felix the Cat in 1919.',
'In 1940, Tom and Jerry starred in the first theatrical cartoon Puss Gets the Boot.',
'In 1981 Andrew Lloyd Weber created the musical Cats, based on T.S. Eliot\'s Old Possum\'s Book of Practical Cats.',
'The normal body temperature of a cat is between 100.5 and 102.5 Fahrenheit.',
'A cat has 230 bones in its body. A human has 206. A cat has no collarbone, so it can fit through any opening the size of its head.',
'A cat\'s nose pad is ridged with a unique pattern, just like the fingerprint  of a human.',
'If they have ample water, cats can tolerate temperatures up to 133 &deg;F.',
'Foods that should not be given to cats include onions, garlic, green tomatoes, raw potatoes, chocolate, grapes, and raisins.',
 'Feeding cats dog food or canned tuna that\'s for human consumption can cause malnutrition.',
'A 2007 Gallup poll revealed that both men and women were equally likely to own a cat.',
'A cat\'s heart beats nearly twice as fast as a human heart, at 110 to 140 beats a minute.'
]

CatFacts.getFact = function() {
	catFact = Math.floor(Cryptocat.random() * interestingFacts.length)
	while (lastCatFact === catFact) {
		catFact = Math.floor(Cryptocat.random() * interestingFacts.length)
	}
	lastCatFact = catFact
	return interestingFacts[catFact]
}

})()